version: "3"

services:
  db:
    image: "mongo:4.0.5"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always
  api:
    build: ./api/
    ports:
      - 3050:3050
    depends_on:
      - db
  frontend:
    build: ./frontend/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

